#!/bin/bash

#SYSTEM
alias cdf='cd (fdfind --type directory | fzf)'
alias ll='ls -l'
alias la='ls -al'
alias f='fish'
alias reload='source ~/.config/fish/config.fish'
alias up1='sudo nala update'
alias up2='sudo nala list --upgradable'
alias up3='sudo nala upgrade -y ; flatpak update -y'

# software launchers
alias mc='mc -b'
alias hugin='bash /home/soleus/Documents/School/master/AI_logika/HUGIN_LITE_64.ubuntu-22.04/bin/hugin'
alias rapidminer='sh ~/Documents/rapidminer/rapidminer-studio-10.1.1/rapidminer-studio/RapidMiner-Studio.sh'
alias n='nvim .'

#Logmanager
alias vm='echo "curl -s https://raw.githubusercontent.com/to23mas/dev-tools/refs/heads/main/script.sh | bash" | xclip -selection c && echo "CURL copied"'
alias bssh='ssh -t micka@dev-bastion.dev.office.ad --'
alias bsshclear='bssh --osh selfForgetHostKey --port22 --host'

alias ruleset='php vendor/bin/phpcs --config-set default_standard ruleset.xml'

# repl aliases
alias python='python3'
alias py='python3'
alias e='elixirc'

# git
alias lg='lazygit'
alias gane='git --amend --no-edit'
alias gch="git checkout (git branch | fzf | tr -d '[:space:]')"
alias gcap='git commit --amend --no-edit ; git push --force'
alias ga='git add .'
alias gp='git push'

# docker
alias dpr='sudo docker system prune -a -f ; sudo docker volume prune'
alias drm='docker stop (docker ps -aq) ; docker rm (docker ps -aq)'
alias dc='docker compose'
alias drud='drm && dcud'
alias de='docker exec -it'
alias dcu='docker compose up'
alias dcud='docker compose up -d'
alias dps='docker ps -a'
alias dl='docker logs -f'
alias fpm-user='docker exec -it fpm php bin/console db:createUser admin-tom admin'

# make
alias m='make'
alias cc='make cc'
alias cs='make cs'
alias csf='make csf'
alias stan='make stan'

alias at='echo -n "vendor/bin/tester -C tests/acceptance/JsonRpc/" | xclip -selection c ; docker compose -f docker-compose.yml -f docker-compose.test.yml run test bash'
alias it='echo -n "vendor/bin/tester -C tests/integration/Sso/" | xclip -selection c ; docker compose -f docker-compose.yml -f docker-compose.test.yml run test bash'

alias ut='vendor/bin/tester -C tests/unit/'

# jumps
alias coursera='cd /home/soleus/Documents/Programming/Coursera/Algorithmic/'
alias pico='nvim /media/soleus/CIRCUITPY/code.py'
alias side='cd ~/Documents/side/Husite-nette/'
alias school='cd /home/soleus/Documents/School/master/'
alias vault='cd ~/Documents/obsidian/knowledge'
alias conf='cd ~/.config'
alias programming='cd ~/Documents/Programming/'
alias master='cd ~/Documents/School/master'
alias django='cd ~/Documents/School/master/django'
alias svatek='cd ~/Documents/School/master/svatek/projekt/'
alias aoc='cd ~/Documents/Programming/aoc/clojure-23'

# config shortcuts
alias aliases='nvim ~/.config/aliases/personal'
alias nvimconf='cd ~/.config/nvim/ ; nvim .'

# launchers
alias wezterm='flatpak run org.wezfurlong.wezterm'

# TMUX
alias x='tmuxinator start'
alias ta='tmux a'
alias t='tmux new-session -As $(basename "$PWD")'
alias ts='. ~/.config/scripts/tmux/tmux_session'
